### ISSUE TITLE
Retrieving api doc differs from spec

### ISSUE THREAD

**Issue by allanfrankwork** [opengeospatial/ets-ogcapi-edr10#109]
Thanks for an excellent test suite! We've been using the ogcapi-features test suite and are beginning to use ets-ogcapi-edr10 for an EDR service.

**Describe the bug**
The EDR spec requires the api documentation to be available in EDR Requirement A.74/Abstract Test 5 and the test suite tests for this in ApiDefinition.apiDefinitionValidation(). However when the apimodel is used in other tests, it is retrieved using another function in CommonDataFixture.retrieveApiModel. This function does not use the same method for getting the api model - it appends f=application/json to the api model instead of passing the Accept header with application/vnd.oai.openapi+json;version=3.0

I believe this is an error and that the service documentation should be retrieved using same procedure as the A.74/Abstract Test 5 test does.
The f=application/json looks like something for the EDR metadata endpoints, not for API service documentation.

**To Reproduce**
1. Execute the testng.xml against a service
2. Monitor the endpoint described by service-desc (/api for exampl) for calls

**Expected behavior**
When service documentation in json format is required, Accept header should specify application/vnd.oai.openapi+json;version=3.0, and no queryparameter named 'f'.

**Comment by afasseco** [comment]
Forgot to add that I was able to work around this issue by adding the apidefinition as a dependency:

@Test(description = "Implements Abstract Test 82, meets Requirement /req/collections/rc-md-op", dataProvider = "collectionsUris", dependsOnGroups = {"conformance","**apidefinition**"})
public void validateCollectionsMetadataOperation(TestPoint testPoint) {

and replacing the CommonDataFixture.retrieveApiModel with:

	@BeforeClass
	public void retrieveApiModel(ITestContext testContext) {

		modelUri = (URI) testContext.getSuite().getAttribute(SuiteAttribute.API_DEFINITION.getName());

		boolean validate = false;
		this.apiModel = (OpenApi3) testContext.getSuite().getAttribute( API_MODEL.getName() );
	}

which uses the model retrieved in the API definition.

Please let me know if you want a PR with this.

Thanks.

**Comment by dstenger** [comment]
Thank you for reporting. We will look into this and come back to you.
