### ISSUE TITLE
OGC API - EDR ETS: Testing for "coords" within Cube Query, Should be bbox

### ISSUE THREAD

**Issue by ShaneMill1** [opengeospatial/ets-ogcapi-edr10#112]
In testing the EDR ETS, There is a failed test for the "coords" query parameter for the Cube query. According to the specification, there is no "coords" query parameter, but rather a "bbox" query parameter. See screenshot for failed test. See this issue for additional context:

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/423

![ets_cube_fail](https://github.com/opengeospatial/ets-ogcapi-edr10/assets/43827821/2a7e36a3-1eb9-44cd-a04a-ac0d7e2ab2a2)

**Comment by dstenger** [comment]
Thank you for reporting. We will do further research.

**Comment by ghobona** [comment]
@ShaneMill1 Agreed. The ETS will be updated.

**Comment by murithigeo** [comment]
I am getting the same error even if the bbox parameter is actually defined.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/af9731af-a287-4a21-b390-05fdc31af0ab" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5c251e77-6bf1-4ad2-9a3c-570beda75018" />
