### ISSUE TITLE
Testing for GeoJSON even though API doesn't claim to support GeoJSON

### ISSUE THREAD

**Issue by ways** [opengeospatial/ets-ogcapi-edr10#114]
**Describe the bug**
When I test my API with the validator, I get two errors regarding GeoJSON support. My API doesn't use GeoJSON, only CoverageJSON. I think these tests should be skipped rather than fail.

**To Reproduce**
1. Run validator for the api given by https://github.com/metno/edrisobaric/
2. View error report

**Expected behavior**
Skip GeoJSON tests when API doesn't support GeoJSON in output_formats.

**Screenshots**
```
            "data_queries": {
                "position": {
                    "link": {
                        "href": "http://localhost:5000/collections/isobaric/position",
                        "rel": "data",
                        "variables": {
                            "query_type": "position",
                            "output_formats": [
                                "CoverageJSON"
                            ],
                            "default_output_format": "CoverageJSON"
                        }
                    }
                }
```

**Additional context**
Output from test:

<h2>GeoJSON</h2>

Pass:                   0 | Fail:                   1 | Skip:                   0 | Total tests:                   1
-- | -- | -- | --

Name|Reason
-- | --
validate Response For GeoJSON|Fails Abstract Test 21. None of the collections were found to offer Locations resources that return valid GeoJSON

<h2>EDRGeoJSON</h2>

Pass:                   0 | Fail:                   1 | Skip:                   0 | Total tests:                   1
-- | -- | -- | --

Name|Reason
-- | --
validate Response For EDRGeoJSON|Fails Abstract Test 23. None of the collections were found to offer Position resources that return GeoJSON conforming to EDR GeoJSON.

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.
