### ISSUE TITLE
 Result: java.net.NoRouteToHostException: No route to host (Host unreachable)

### ISSUE THREAD

**Issue by murithigeo** [opengeospatial/ets-ogcapi-edr10#132]
**Describe the bug**
Unable to run any tests. The [features test suite](https://opengeospatial.github.io/ets-ogcapi-features10/#:~:text=HTTP%20calls%20to%20localhost%20are%20not%20working%20with%20Docker.%20You%20need%20to%20make%20calls%20using%20host%20IP%20(ipconfig%20on%20Windows%20or%20ifconfig%20on%20Unix%20based%20OS%20like%20Linux%20or%20Mac)) recommends using the LAN IP since connection to localhost is restricted.
The test suite refuses to run stating 
```
Result:
java.net.NoRouteToHostException: No route to host (Host unreachable)
```
I don't know if its a bug considering that I've just run features test before
**To Reproduce**
1. Pull the official docker image and run it.
2. Connect and use the LAN IP of desktop/localhost as address.

**Expected behavior**
To connect and start tests

**Additional context**
Log files: 
[s0003.zip](https://github.com/user-attachments/files/17118138/s0003.2.zip)

**Comment by dstenger** [comment]
Thank you for reporting.
This is most likely a problem inside your network. You must make sure that the service is reachable from the Docker Container. Is the Docker Container running in the same network as the IP you were using (e.g. Container is started on your local machine)?
You could try to login to Docker Container (docker exec -it CONTAINER_NAME bash) and check if your API is reachable from there.

**Comment by murithigeo** [comment]
Yeah. Its a problem on the network. When listening on hostIP and testing using the Features ETS, it works fine.
The solution was to listen on `host.docker.internal`
