### ISSUE TITLE
Abstract Test 136 seemingly incorrect

### ISSUE THREAD

**Issue by tiaanwessels** [opengeospatial/ets-ogcapi-edr10#138]
**Describe the bug**
Abstract Test 136 expects 400 in the response but the OGC EDR specification states under /conf/locations/no-query-params:
Validate that a GeoJSON document was returned with a status code 200 containing at least a list of features one for each location supported by the collection

**To Reproduce**
1. Run the test case against an implementation with a locations query for a collection that responds with a GeoJSON document and code 200 to see the problem

**Expected behavior**
I expected a PASS when the service responds with GeoJSON and code 200

**Screenshots**

**Additional context**
This is the returned GeoJSON
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "coordinates": [
                    21,
                    52.25
                ],
                "type": "Point"
            },
            "properties": {
                "locationId": "EPWW",
                "locationName": "ACC"
            }
        }
    ]
}
and this the headers
Request URL:
http://swim:12373/edr/collections/airmet/locations
Request Method:
GET
Status Code:
200 OK
Remote Address:
192.168.51.118:12373
Referrer Policy:
strict-origin-when-cross-origin

and the test result (truncated) looks like

<test-method status="FAIL" signature="validateNoQueryParameters(java.lang.Object)[pri:0, instance:org.opengis.cite.ogcapiedr10.queries.QueryCollections@1f0f1111]" name="validateNoQueryParameters" duration-ms="39" started-at="2024-10-23T10:20:27Z" description="Implements Abstract Test 34 (/conf/position), Abstract Test 50 (/conf/area), Abstract Test 66 (/conf/cube), Abstract Test 82 (/conf/trajectory), Abstract Test 100 (/conf/corridor), Abstract Test 136 (/conf/locations) " data-provider="collectionIDs" finished-at="2024-10-23T10:20:27Z">
<params>
<param index="0">
<value>
<![CDATA[ [airmet, metar, vaa, taf, opmet, sigmet] ]]>
</value>
</param>
</params>
<exception class="java.lang.AssertionError">
<message>
<![CDATA[ Fails Abstract Test 136. Expected status code 400 when a Locations query with no query parameters are specified for collection airmet ]]>
</message>
</exception>

<reporter-output> </reporter-output>
...

**Comment by dstenger** [comment]
Thank you for reporting.
I understand your problem and we will check the implementation of the test suite.
Is it possible to provide a public API we can use to reproduce the problem?
