### ISSUE TITLE
Implements Abstract Test 70 seemingly incorrect

### ISSUE THREAD

**Issue by tiaanwessels** [opengeospatial/ets-ogcapi-edr10#140]
**Describe the bug**
Test 70 seeks a coords parameter in cube but /conf/edr/rc-coords-definition is not required for cube according to https://docs.ogc.org/is/19-086r6/19-086r6.html (only position, area, trajectory, corridor)

**To Reproduce**
Run test against service not specifying cube coords in API definition

**Expected behavior**
Not test this at all

**Screenshots**

**Additional context**
<message>
<![CDATA[ Required coords parameter for collections with path '/cube' in OpenAPI document is missing expected object to not be null ]]>
</message>

**Comment by dstenger** [comment]
Thank you for reporting. We will check the test suite regrading your problem.
Is it possible to provide a public API we can use to reproduce the problem?

**Comment by tiaanwessels** [comment]
Unfortunately not, i have no public facing infrastructure to host it on,
apologies.

**Comment by bpross-52n** [comment]
Possible dupliacte of #112

**Comment by bpross-52n** [comment]
@tiaanwessels The fix for #112 is in beta (https://cite.ogc.org/te2/) and Docker Hub (https://hub.docker.com/r/ogccite/ets-ogcapi-edr10) could you re-run your tests and check if the error still occurs?

**Comment by tiaanwessels** [comment]
Unfortunately this has become a bit blurred for me now. In the additional context section when reporting the problem i was not aware that i had to quote the XML i pasted as code so the report 'lost' that context and now i can't figure out if  this report of mine was in fact the same thing as my issue reported under #143. Regardless, perhaps the cubeBboxParameterDefinition test's description is what lead me astray on the first iteration. It is listed as: Implements Abstract Test 70 (/conf/edr/rc-coords-definition) but then the test actually goes on to see if the bbox is a string instead of an array as it should be. So, i have a suspicion in hind-sight that what i meant to report i in this case i did in fact report later on in 143 (which is still a bug IMHO in that the test suite is checking bbox to be string rather than array even when checking out the test suite from the head). So, i think it would be appropriate to close this issue and retain only 143 if you agree with my assessment.

**Comment by tiaanwessels** [comment]
Perhaps it is also prudent that you confirm that checking out of the latest test suite is correct. Is this how:

> git clone https://github.com/opengeospatial/ets-ogcapi-edr10.git

**Comment by bpross-52n** [comment]
Yes, cloning master will get you the most recent version of the test suite. I am ok with closing this issue and I will work on #143 now.

> Perhaps it is also prudent that you confirm that checking out of the latest test suite is correct. Is this how:
> 
> > git clone https://github.com/opengeospatial/ets-ogcapi-edr10.git
> 
> I mean, is this clone how one would retrieve the latest bug fixes in beta ?
