### ISSUE TITLE
validateAreaQueryUsingParameters throw exception

### ISSUE THREAD

**Issue by tiaanwessels** [opengeospatial/ets-ogcapi-edr10#141]
**Describe the bug**
Test throws exception rather than come to useful conclusion

**To Reproduce**
Run test against a service which returns the result as in the 'Additional context'

**Expected behavior**
Show proper failure text

**Screenshots**

**Additional context**
<test-method status="FAIL" signature="validateAreaQueryUsingParameters(java.lang.Object)[pri:0, instance:org.opengis.cite.ogcapiedr10.queries.QueryCollections@1f0f1111]" name="validateAreaQueryUsingParameters" duration-ms="21" started-at="2024-10-23T10:20:27Z" description="Implements Abstract Test 53 (/conf/area), Abstract Test 55 (/conf/edr/rc-coords-response), Abstract Test 57 (/conf/edr/rc-z-response), Abstract Test 59 (/conf/core/datetime-response), Abstract Test 61 (/conf/edr/rc-parameter-name-response), Abstract Test 63 (/conf/edr/REQ_rc-crs-response), Abstract Test 65 (/conf/collections/rc-f-response)" data-provider="collectionIDs" finished-at="2024-10-23T10:20:27Z">
<params>
<param index="0">
<value>
<![CDATA[ [airmet, metar, vaa, taf, opmet, sigmet] ]]>
</value>
</param>
</params>
<exception class="java.util.NoSuchElementException"> </exception>

<reporter-output> </reporter-output>
<attributes>
<attribute name="request">
<![CDATA[ Request method: GET Request URI: http://swim:12373/edr/collections/airmet Proxy: <none> Request params: <none> Query params: <none> Form params: <none> Path params: <none> Headers: Accept=application/json, application/javascript, text/javascript, text/json Cookies: <none> Multiparts: <none> Body: <none> ]]>
</attribute>

<attribute name="response">
<![CDATA[ HTTP/1.1 200 OK Connection: Keep-Alive Content-Length: 8193 Content-Type: application/json Access-Control-Allow-Headers: Content-Type, Content-Length Access-Control-Allow-Methods: GET, POST, PUT, DELETE Access-Control-Allow-Origin: * Date: Wed, 23 Oct 2024 10:20:27 GMT { "id": "airmet", "title": "AIRman's METeorological Information", "description": "AIRMETs coded in IWXXM", "links": [ { "href": "http://swim:12373/edr/collections/airmet", "rel": "self", "type": "application/json", "title": "Collection metadata as per https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/collections/collection.yaml" }, { "href": "http://swim:12373/edr/collections/airmet/radius", "rel": "data", "type": "application/json", "title": "Where to get the data from for the collection" } ], "keywords": [ "AIRMET", "IWXXM" ], "extent": { "spatial": { "bbox": [ [ -180, -90, 180, 90 ] ], "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84" }, "temporal": { "interval": [ [ "1900-01-00T00:00:00Z", "1900-01-00T00:00:00Z" ] ], "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian" } }, "crs": [ "http://www.opengis.net/def/crs/OGC/1.3/CRS84" ], "output_formats": [ "TAR" ], "data_queries": { "radius": { "link": { "href": "http://swim:12373/edr/collections/airmet/radius", "rel": "data", "title": "Radius Query", "templated": false, "variables": { "title": "Radius Query", "description": "Data within distance from centre", "query_type": "radius", "output_formats": [ "TAR" ], "default_output_format": "TAR", "within_units": [ "m", "km", "ft", "mi", "nm" ], "crs_details": [ { "crs": "CRS:84", "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" } ] } } }, "area": { "link": { "href": "http://swim:12373/edr/collections/airmet/area", "rel": "data", "title": "Area Query", "templated": false, "variables": { "title": "Area Query", "description": "Data within polygonal area", "query_type": "area", "output_formats": [ "TAR" ], "default_output_format": "TAR", "crs_details": [ { "crs": "CRS:84", "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" } ] } } }, "cube": { "link": { "href": "http://swim:12373/edr/collections/airmet/cube", "rel": "data", "title": "Cube Query", "templated": false, "variables": { "title": "Cube Query", "description": "Data within 4D cube", "query_type": "cube", "output_formats": [ "TAR" ], "default_output_format": "TAR", "crs_details": [ { "crs": "CRS:84", "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" } ] } } }, "corridor": { "link": { "href": "http://swim:12373/edr/collections/airmet/corridor", "rel": "data", "title": "Corridor Query", "templated": false, "variables": { "title": "Corridor Query", "description": "Data within corridor", "query_type": "corridor", "output_formats": [ "TAR" ], "default_output_format": "TAR", "width_units": [ "m", "km", "ft", "mi", "nm" ], "crs_details": [ { "crs": "CRS:84", "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" } ] } } }, "locations": { "link": { "href": "http://swim:12373/edr/collections/airmet/locations", "rel": "data", "title": "Locations Query", "templated": false, "variables": { "title": "Locations Query", "description": "Data from named location", "query_type": "locations", "output_formats": [ "TAR" ], "default_output_format": "TAR", "crs_details": [ { "crs": "CRS:84", "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]" } ] } } } }, "parameter_names": { } } ]]>
</attribute>

</attributes>
</test-method>

**Comment by dstenger** [comment]
Thank you for reporting. We will check the test suite regrading your problem.
Is it possible to provide a public API we can use to reproduce the problem?

**Comment by tiaanwessels** [comment]
Unfortunately not, i have no public facing infrastructure to host it on,
apologies.

**Comment by tiaanwessels** [comment]
It seems some xml that could be useful has been truncated by the ticketing system looking at the report now. I attach the test-method xml as zip
[a.zip](https://github.com/user-attachments/files/17501912/a.zip)
