### ISSUE TITLE
validateCorridorQueryUsingParameters throws exception

### ISSUE THREAD

**Issue by tiaanwessels** [opengeospatial/ets-ogcapi-edr10#142]
**Describe the bug**
validateCorridorQueryUsingParameters throws exception barring one from seeing PASS or FAIL conclusion

**To Reproduce**
Run against service responding as per the attachment in additional context

**Expected behavior**
Not throw exception but conclude the test

**Screenshots**

**Additional context**
[a.zip](https://github.com/user-attachments/files/17502848/a.zip)

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.
