### ISSUE TITLE
cubeBboxParameterDefinition test seemingly incorrect

### ISSUE THREAD

**Issue by tiaanwessels** [opengeospatial/ets-ogcapi-edr10#143]
**Describe the bug**
The test seems to expect a cube's bbox to be a string but as per the screenshot, the spec says it's an array which makes more sense anyway. The error report is:
`Expected property 'schema -> type' with value 'string' but was 'array' expected [string] but found [array]`

**To Reproduce**
Run against a service which defines bbox as string instead of array

**Expected behavior**
Test for it to be an array, not a string

**Screenshots**
![Screenshot from 2024-10-24 07-37-06](https://github.com/user-attachments/assets/43e7f0c0-0f42-423e-af8f-7913b1a68e81)

**Additional context**
[a.zip](https://github.com/user-attachments/files/17503024/a.zip)

**Comment by tiaanwessels** [comment]
What is fishy is that the github example shows it as a string which is perhaps where this problem stems from

[https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/request-bodies/cube.yaml](url)

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by tiaanwessels** [comment]
I need to make a correction to the reproduce instructions.
I wrote:
Run against a service which defines bbox as string instead of array
but it should be
Run against a service which defines bbox as array instead of string
