### ISSUE TITLE
ETS errors against pygeoapi implementation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-edr10#5]
Hi: following on from https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/201, my [draft pygeoapi EDR server implementation](https://github.com/tomkralidis/pygeoapi/tree/edr-api) results in the following against a local Docker build of the EDR ETS:

- passed: 106
- failed: 4
- skipped: 0

Failing assertions below:

![image](https://user-images.githubusercontent.com/910430/108647322-5e367900-7486-11eb-97e7-4d56ee82d62e.png)

In my particular case, I am only supporting an area and position query, and as a result it appears as if the errors above are looking for query types which (in my case) are not implemented.

Is an EDR implementation expected to support all query types? cc @m-burgoyne @solson-nws @ShaneMill1 @chris-little

**Comment by m-burgoyne** [comment]
@tomkralidis No, any EDR implementation that supports **one** or more of the following query types can be considered compliant:

**Position
Radius
Area
Cube
Trajectory
Corridor
Item
Location**

The tests will need to be updated to reflect this.

**Comment by ghobona** [comment]
Can we clarify this further to say the following?

If the EDR implementation declares in the OpenAPI definition document that it supports a particular query type, then it shall support that particular query type.

**Comment by tomkralidis** [comment]
+1 (in addition to requiring **one** query type).

**Comment by tomkralidis** [comment]
cc @chris-little

@ghobona / @m-burgoyne would this only be an ETS update, or specification update as well?  My feeling is we would also need to update as a core requirements class and an abstract test? Happy to do this.

**Comment by solson-nws** [comment]
+1

**Comment by ghobona** [comment]
@tomkralidis My initial thinking was that this is an ETS only update. However, a note in the Standard document would provide clarity for future implementers.
