### ISSUE TITLE
ETS handed over to CITE engineers for further development

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-edr10#84]
The ETS has now been handed over to @keshav-nangare for further development. @keshav-nangare is one of the engineers in the Compliance Program.

This note is simply to introduce @keshav-nangare to the API implementers.

https://ogcie.iblsoft.com/edr is managed by @iandruska-ibl

http://geos.whu.edu.cn/whu-edr-demo is managed by @boyi-shangguan

http://labs.metoffice.gov.uk/edr is managed by @m-burgoyne and @chris-little

https://data-api.mdl.nws.noaa.gov/EDR-API is managed by @ShaneMill1 and @solson-nws

https://github.com/tomkralidis/pygeoapi/tree/edr-api is managed by @tomkralidis

**Comment by tomkralidis** [comment]
> https://github.com/tomkralidis/pygeoapi/tree/edr-api is managed by @tomkralidis

Note that the above branch is now deleted (since merged into pygeoapi proper):
- https://github.com/geopython/pygeoapi
- https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-edr.html
