### ISSUE TITLE
Release fails because of maven-antrun-plugin

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-ogcapi-edr10#91]
**Describe the bug**
Release executed with Maven fails because of maven-antrun-plugin.

**To Reproduce**
Jenkins reports the following (http://build.opengeospatial.org/jenkins/view/release/job/ets-ogcapi-edr10-release/1/console):
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.117 s
[INFO] Finished at: 2021-11-26T14:44:28-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project ets-ogcapi-edr10: Cannot prepare the release because you have local modifications : 
[ERROR] [docker/teamengine/WEB-INF/lib/ets-ogcapi-edr10-0.1-SNAPSHOT.jar:modified]
```
The artifact ets-ogcapi-edr10-0.1-SNAPSHOT.jar is copied by the maven-antrun-plugin.

**Expected behavior**
Release build with Maven Release Plugin shall be successful.

**Comment by dstenger** [comment]
Removed maven-antrun-plugin to ensure that release 0.1 can be created: https://github.com/opengeospatial/ets-ogcapi-edr10/commit/46fec6bb8b61d5f04ccde612f20f1741cc521477

**Comment by dstenger** [comment]
I realized that there are two Dockerfiles in this project:
* ./src/docker/Dockerfile
* ./docker/Dockerfile

To finalize this issue, I propose to remove folder: `./docker/`

**Comment by ghobona** [comment]
@dstenger I have just deleted the `./docker` folder.
